name: pcsx_rearmed libretro Linux armhf

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
#  watch: # this is a hack that lets repo owners trigger a build by starring
#    types: [started]
#    if: github.actor == github.event.repository.owner.login

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-20.04

    steps:
    - name: add foreign arch
      run: |
        sudo dpkg --add-architecture armhf
        sudo rm -rf /etc/apt/sources.list
        echo "deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu focal main restricted" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu focal-updates main restricted" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu focal universe" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu focal-updates universe" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu focal multiverse" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu focal-updates multiverse" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=amd64] http://us.archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports focal main restricted" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports focal-updates main restricted" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports focal universe" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports focal-updates universe" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports focal multiverse" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports focal-updates multiverse" | sudo tee -a /etc/apt/sources.list
        echo "deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports focal-backports main restricted universe multiverse"  | sudo tee -a /etc/apt/sources.list
    - name: Install needed packages
      run: sudo apt update && sudo apt install wget:amd64 git:amd64 build-essential:amd64 gcc:amd64 make:amd64 g++-arm-linux-gnueabihf:amd64 gcc-arm-linux-gnueabihf:amd64 binutils-aarch64-linux-gnu:amd64 libx11-dev:armhf libgles2-mesa-dev:armhf libegl-dev:armhf libxext-dev:armhf
    - name: Checkout source
      run: git clone https://github.com/libretro/pcsx_rearmed.git && cd pcsx_rearmed && git submodule update --init
    - name: Build libretro core
      working-directory: pcsx_rearmed
      run: |
        make -f Makefile.libretro -j8 CC=/usr/bin/arm-linux-gnueabihf-gcc CXX=/usr/bin/arm-linux-gnueabihf-g++ platform=classic_armv8_a35
        wget https://raw.githubusercontent.com/libretro/libretro-super/master/retrolink.sh && chmod +x retrolink.sh && ./retrolink.sh pcsx_rearmed_libretro.so
        zip -9 ../pcsx_rearmed_libretro.so.zip pcsx_rearmed_libretro.so
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Linux_armhf
        file: pcsx_rearmed_libretro.so.zip
        overwrite: true
